---
apiVersion: v1
kind: Service
metadata:
  name: titanic-ml-svc
  labels:
    app: titanic-ml
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: titanic-ml